### ISSUE TITLE
It is not marked as "게임중" except for hosts.

### ISSUE THREAD

**Issue by DebugBios** [L-Leite/cso2-master-server#79]
![cso2_0000](https://user-images.githubusercontent.com/44349391/55322254-cce74380-54b6-11e9-8da4-742fc81da5fa.jpg)

**Comment by dounai2333** [comment]
this issue is still unresolved, and new players entering the room will still only see the non-host's status as "Ready". i'm sorry if you have a poor understand of Chinese, but if you look at them carefully, you can still see that these are three different states, the two clients on the right side of the picture are all in the game.

![@2NWCOU2YWN1~X7DPF MG}L](https://user-images.githubusercontent.com/45044404/55728228-43032180-5a46-11e9-9162-1e8fd6f53b91.png)
